name: "Nightly Build"
qon:
  push:
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - run: nix-shell --run "true"
        
    - name: Compile
      run: nix-shell --run "./make.sh"
    - name: Patch elf
      run: nix-shell --run "patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 ./dist/senkora"
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: senkora-linux
        path: ./dist/senkora
        
  Publish:
    runs-on: ubuntu-latest
    needs: [Compile]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Download senkora-linux artifact
        uses: actions/download-artifact@v3
        with:
          name: senkora-linux
      
      - uses: dev-drprasad/delete-tag-and-release@085c6969f18bad0de1b9f3fe6692a3cd01f64fe5
        with:
          delete_release: true
          tag_name: nightly
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
          files: senkora
